services:
  webshell-challenges:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock" 
    # allow starting docker containers from this docker container
    ports: 
      - "8020:8020"

